name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        resolver:
        - lts-20 # ghc-9.2.8
        - lts-21 # ghc-9.4.8
        - lts-22 # ghc-9.6.4

    steps:
    - uses: actions/checkout@v3
    - id: stack
      uses: freckle/stack-action@v4
      with:
        stack-yaml: stack/stack-${{ matrix.resolver }}.yaml
        stack-arguments: --bench --no-run-benchmarks --haddock --no-haddock-deps
